version: 2
jobs:
  build:
    docker:
      - image: golang:1.8

    working_directory: /go/src/github.com/mlabouardy/serverless-go/lambda

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: ls && go get -v

      - run:
          name: Run Unit Tests
          command: go test
